version: "4.0"
services:
  app:
    build:
      context: .
      args:
        - VITE_APP_TEST=BuildValue
    ports:
      - "8082:80"
  app2:
    build:
      context: .
      args:
        - VITE_APP_TEST=BuildValue2
    ports:
      - "8083:80"
